name: MAP_bro
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.3
  - jupyter==1.0.0
  - nb_conda_kernels<2.2.0  # nb_conda_kernels issue #158
  - pandas==1.1.3
  - numpy<1.19.0
  - matplotlib==3.3.2
  - gym==0.17.3
  - pip
  - pip:
    - -e .
